-- spec/status_spec.lua — pure status-display decision logic (partyhud_status)
local M = require("partyhud_status")

-- mirror the game's RATE_SCALE enum (constants.lua:2402)
local RS = {
  NEUTRAL = 0,
  INCREASE_HIGH = 1,
  INCREASE_MED = 2,
  INCREASE_LOW = 3,
  DECREASE_HIGH = 4,
  DECREASE_MED = 5,
  DECREASE_LOW = 6,
}

describe("partyhud status — sanity_ratescale", function()
  describe("asleep (GetRateScale reads NEUTRAL; level synthesized from the sleep gain rate)", function()
    -- raw_rs is passed as NEUTRAL while asleep (ignored by the sleep branch); pct < 1.
    it("rate > .2 -> INCREASE_HIGH", function()
      assert.are.equal(RS.INCREASE_HIGH, M.sanity_ratescale(true, 0.5, RS.NEUTRAL, 0.5, RS))
    end)
    it("rate in (.1, .2] -> INCREASE_MED", function()
      assert.are.equal(RS.INCREASE_MED, M.sanity_ratescale(true, 0.15, RS.NEUTRAL, 0.5, RS))
      assert.are.equal(RS.INCREASE_MED, M.sanity_ratescale(true, 0.2, RS.NEUTRAL, 0.5, RS)) -- boundary: .2 is NOT > .2
    end)
    it("rate in (.01, .1] -> INCREASE_LOW", function()
      assert.are.equal(RS.INCREASE_LOW, M.sanity_ratescale(true, 0.05, RS.NEUTRAL, 0.5, RS))
      assert.are.equal(RS.INCREASE_LOW, M.sanity_ratescale(true, 0.1, RS.NEUTRAL, 0.5, RS)) -- boundary
    end)
    it("rate <= .01 -> NEUTRAL", function()
      assert.are.equal(RS.NEUTRAL, M.sanity_ratescale(true, 0.005, RS.NEUTRAL, 0.5, RS))
      assert.are.equal(RS.NEUTRAL, M.sanity_ratescale(true, 0, RS.NEUTRAL, 0.5, RS))
    end)
    it("at full sanity (pct >= 1) -> NEUTRAL even with a high sleep rate", function()
      assert.are.equal(RS.NEUTRAL, M.sanity_ratescale(true, 0.5, RS.NEUTRAL, 1, RS))
      assert.are.equal(RS.NEUTRAL, M.sanity_ratescale(true, 0.5, RS.NEUTRAL, 1.0, RS))
    end)
  end)

  describe("awake (use the game's rate enum, clamped at the extremes)", function()
    it("an INCREASE level shows when not full, NEUTRAL at full", function()
      assert.are.equal(RS.INCREASE_HIGH, M.sanity_ratescale(false, 0, RS.INCREASE_HIGH, 0.5, RS))
      assert.are.equal(RS.INCREASE_MED, M.sanity_ratescale(false, 0, RS.INCREASE_MED, 0.99, RS))
      assert.are.equal(RS.INCREASE_LOW, M.sanity_ratescale(false, 0, RS.INCREASE_LOW, 0.01, RS))
      -- no rising arrow at full
      assert.are.equal(RS.NEUTRAL, M.sanity_ratescale(false, 0, RS.INCREASE_HIGH, 1, RS))
    end)
    it("a DECREASE level shows when not empty, NEUTRAL at empty", function()
      assert.are.equal(RS.DECREASE_HIGH, M.sanity_ratescale(false, 0, RS.DECREASE_HIGH, 0.5, RS))
      assert.are.equal(RS.DECREASE_MED, M.sanity_ratescale(false, 0, RS.DECREASE_MED, 0.01, RS))
      assert.are.equal(RS.DECREASE_LOW, M.sanity_ratescale(false, 0, RS.DECREASE_LOW, 1, RS))
      -- no falling arrow at empty
      assert.are.equal(RS.NEUTRAL, M.sanity_ratescale(false, 0, RS.DECREASE_HIGH, 0, RS))
    end)
    it("a NEUTRAL game rate -> NEUTRAL", function()
      assert.are.equal(RS.NEUTRAL, M.sanity_ratescale(false, 0, RS.NEUTRAL, 0.5, RS))
    end)
  end)
end)

describe("partyhud_status — temp_popup", function()
  it("comfortable band -> hidden", function()
    local show = M.temp_popup(35, 0)
    assert.is_false(show)
  end)
  it("cold danger band -> shown, kind cold", function()
    local show, kind = M.temp_popup(5, 0)
    assert.is_true(show)
    assert.are.equal("cold", kind)
  end)
  it("hot danger band -> shown, kind hot", function()
    local show, kind = M.temp_popup(65, 0)
    assert.is_true(show)
    assert.are.equal("hot", kind)
  end)
  it("fast cooling in the comfortable band -> shown cold", function()
    local show, kind = M.temp_popup(35, -2)
    assert.is_true(show)
    assert.are.equal("cold", kind)
  end)
  it("fast warming -> shown hot", function()
    local show, kind = M.temp_popup(35, 2)
    assert.is_true(show)
    assert.are.equal("hot", kind)
  end)
  it("nil current -> hidden", function()
    assert.is_false((M.temp_popup(nil, 0)))
  end)
  it("explicit thresholds override defaults", function()
    assert.is_false((M.temp_popup(20, 0, 10, 60, 1)))
    assert.is_true((M.temp_popup(20, 0, 25, 60, 1)))
  end)
end)

describe("partyhud_status — moisture_popup", function()
  it("dry (0) -> hidden", function()
    assert.is_false(M.moisture_popup(0))
  end)
  it("nil -> hidden", function()
    assert.is_false(M.moisture_popup(nil))
  end)
  it("wet (>0) -> shown", function()
    assert.is_true(M.moisture_popup(1))
  end)
end)
